# Generated by Django 6.0.3 on 2026-03-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressconfig",
            options={
                "verbose_name": "Address configuration",
                "verbose_name_plural": "Address configuration",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="addressconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="PropertyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_for_sale", models.BooleanField(default=False)),
                (
                    "sale_type",
                    models.CharField(
                        blank=True, help_text="auction, sale, etc.", max_length=50
                    ),
                ),
                (
                    "price_info",
                    models.CharField(
                        blank=True,
                        help_text="Price, guide, or 'contact agent'",
                        max_length=200,
                    ),
                ),
                ("next_inspection", models.DateTimeField(blank=True, null=True)),
                ("auction_date", models.DateTimeField(blank=True, null=True)),
                ("last_sale_price", models.CharField(blank=True, max_length=100)),
                ("scraped_at", models.DateTimeField(auto_now=True)),
                (
                    "source_domain",
                    models.CharField(
                        help_text="domain.com.au or realestate.com.au", max_length=100
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_info",
                        to="addresses.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Information",
                "verbose_name_plural": "Property Information",
            },
        ),
    ]
